my_book_store/book_renting/api/urls.py
from django.contrib import admin
from django.urls import path,include
from book_renting.api import urls
from . import views
app_name='Book_renting'
urlpatterns=[
    path('add',views.add_book.as_view(),name='add'),
    path('rent/view_all',views.rented_book.as_view(),name='rent'),
    path('view',views.view_book.as_view(),name='view'),
    path('search/<str:bookname>',views.search_books.as_view(),name='search'),
    path('rent/rent_a_book',views.rent_book.as_view(),name='renting'),
    path('rent/email/<str:emailid>',views.rented_book_using_email.as_view(),name='emailsearch')
]

my_book_store/frontend/urls.py
from django.urls import include,path
from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
      path
      ('', views.home, name='home'),
    
    path
    ('signup/', views.signup, name='signup'),
        path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',  
        views.activate, name='activate'),  
        path('login/',views.Login,name='login'),
        path('logout',views.Logout,name='logout'),
    
]

my_book_store/my_book_store/urls.py
from django.contrib import admin
from django.urls import path,include
from book_renting.api import urls
app_name='main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/',include('book_renting.api.urls')),
    path('user/',include('frontend.urls'))
]

my_book_store/frontend/models.py
from django.db import models

class user(models.Model):
     username=models.CharField(max_length=50)
     password=models.CharField(default='ankush',max_length=50)
     first_name = models.CharField(max_length=200)
     second_name = models.CharField(max_length=200)
     email = models.EmailField(max_length=100)

my_book_store/frontend/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
class LoginForm(forms.Form):
    username=forms.CharField(required=True)
    password=forms.CharField(required=True,widget=forms.PasswordInput())

my_book_store/frontend/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import SignupForm,LoginForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
import json
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from rest_framework.permissions import IsAuthenticated
from rest_framework.decorators import api_view, permission_classes





def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            print(user.pk)
            current_site = get_current_site(request)
            message = render_to_string('frontend/Email_template.html', {
                'user':user, 'domain':current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
                
            })
            # Sending activation link in terminal
            # user.email_user(subject, message)
            print(account_activation_token.make_token(user))
            mail_subject = 'Activate your account.'
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration.')
            # return render(request, 'acc_active_sent.html')
    else:
        form = SignupForm()
    return render(request, 'frontend/signup.html', {'form': form})


def activate(request,uidb64,token):
     try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
     except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
     if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        print("email verified")
        user.save()
        login(request, user)
        print("higigi")
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
     else:
        return HttpResponse('Activation link is invalid!')

def Login(request):
     if request.method == "POST":
        form = LoginForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]
            print(username)
            print(password)
            user = authenticate(request, username=username, password=password)
            print(user)
            if user is not None:
                print('hi')
               # messages.success(request, f' welcome {username} !!')
                login(request, user)
                return redirect('home')
        return HttpResponse("error")
    # if a GET (or any other method) we'll create a blank form
     else:
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('home'))
        form = LoginForm()
        return render(request, "frontend/login.html", {"form": form})
def Logout(request):
    logout(request)
    return redirect('login/')
@api_view(['GET'])
@permission_classes((IsAuthenticated, ))
def home(request):
    permission_classes=[IsAuthenticated]
    user =request.user
    return render(request,"frontend/homepage.html",{"user":user})

my_book_store/frontend/templates/frontend/Email_template.html
{% autoescape off %}
Hi ,
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

my_book_store/frontend/templates/frontend/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'home' %} <!  chanage this to activation link using uid and token later!>
{% endautoescape %}

my_book_store/frontend/templates/frontend/acc_active_sent.html
{% extends 'base.html' %}

{% block content %}
  <p>Please confirm your email address to complete the registration. </p>
{% endblock %}

my_book_store/frontend/templates/frontend/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Django Project{% endblock %}</title>
  </head>
  <body>
    <header>
      <h1>My Site</h1>
        <a href="{% url 'signup' %}">signup</a>

      <hr>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
  </body>
</html>

my_book_store/frontend/templates/frontend/home.html
{% extends 'base.html' %}

{% block content %}
  <h2>Welcome, {{ user.get_full_name }} <small>{{ user.username }}</small>!</h2>
  <p>Your email address: {{ user.email }}</p>
{% endblock %}

my_book_store/frontend/templates/frontend/homepage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Django Project{% endblock %}</title>
  </head>
  <body>
    <header>
        <h1> HI {{user}} Welcome to Book Store</h1>
        <br></br>
      <h1></h1>
      <a href="{%url 'Book_renting:view'%}">See all books Available</a>
      <a href="{%url 'Book_renting:add'%}">Add a book</a>
      <a href="{%url 'Book_renting:rent'%}">See all rented books</a>
      <a href="{%url 'Book_renting:renting'%}">Rent a book</a>
      <a href="{%url 'logout'%}">Logout</a>
      <hr>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
  </body>
</html>

my_book_store/frontend/templates/frontend/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Django Project{% endblock %}</title>
  </head>
  <body>
    <header>
      <h1>My Site</h1>
        <a href="{% url 'signup' %}">signup</a>
        <a href ="{%url 'login'%}">login</a>
      <hr>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
  </body>
</html>

my_book_store/frontend/templates/frontend/login.html
{% block content %}
  <h2>login</h2>

  <form method="post">
    {% csrf_token %}
  {{form}}

    <button type="submit">Login</button>
    <a href={% url 'signup' %}>sign up</a>
  </form>
{% endblock %}

my_book_store/frontend/templates/frontend/signup.html
{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
      {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="display: none">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
      {% endfor %}

    <button type="submit">Sign up</button>
  </form>
{% endblock %}